### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by mrinalraj** [ishanjain28/query-extractor#1]
```
ReferenceError: window is not defined
    at Object.getQueryObject [as getAll] (D:\Projects\facebook-post-service\node_modules\query-extractor\index.js:16:28)
    at router.get (D:\Projects\facebook-post-service\routes\auth.js:10:20)
    at Layer.handle [as handle_request] (D:\Projects\facebook-post-service\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\Projects\facebook-post-service\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Projects\facebook-post-service\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Projects\facebook-post-service\node_modules\express\lib\router\layer.js:95:5)
    at D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:174:3)
    at router (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (D:\Projects\facebook-post-service\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:317:13)
    at D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Projects\facebook-post-service\node_modules\express\lib\router\index.js:275:10)
```

**Comment by ishanjain28** [comment]
This module is intended to be used in browsers. Getting Query parameter on server is trivial.
